### ISSUE TITLE
Navigation Note

### ISSUE THREAD

**Issue by cvocode** [adrienlo/cvo#32]
Basically that orange box from the left corner would align above WORK instead of left corner.. and then same when they click on LIFE.
<img width="1895" alt="screen shot 2016-09-08 at 1 53 53 pm" src="https://cloud.githubusercontent.com/assets/13800972/18366501/c5be9a08-75cb-11e6-80cf-6313a3def5ad.png">

**Comment by adrienlo** [comment]
Not sure I understand this? Can you update the comp of what you want?

**Comment by cvocode** [comment]
Oh yeah! Its like this on work. Notice how that orange box moves to the right to hover over WORK. When home it goes back to the left corner...
<img width="750" alt="screen shot 2016-09-20 at 11 15 46 am" src="https://cloud.githubusercontent.com/assets/13800972/18683072/98cd96be-7f23-11e6-9c3b-d18eb8a0c616.png">
